### ISSUE TITLE
Some questions about the reported test accuracy

### ISSUE THREAD

**Issue by MichaelLee-ceo** [ZhangLin-PKU/FedFTG#2]
Thanks for your great work!
I have some questions about the test accuracy.
The code outputs the test accuracy for three cases (test sel / test all / test ft).
Which of the two is the accuracy in the performance table of the paper? ("test all"/ "test ft")

Moreover, I have observed that the performance of the global model **after** fine-tuning often tends to have lower accuracy than **before** fine-tuning. Is this considered correct, or how can this result be explained?

```
**** Communication all   8, Test Accuracy: 0.6960, Loss: 0.8621
**** Communication all   8, Cent Accuracy: 0.7173, Loss: 0.7935
**** Communication ft   8, Test Accuracy: 0.6533, Loss: 0.9915
**** Communication ft   8, Cent Accuracy: 0.6725, Loss: 0.9133
```

**Comment by ZhangLin-PKU** [comment]
Hi MichaelLee-ceo, thank you for following this work. For your questions,

1.  "test all" is used in the paper. 
2. The same phenomenon occurs in my experiments. Theoretically, after fine-tuning the performance should increase. However, fine-tuning can benefit global model if checking performance on next round. Currently I have no idea on it and didn't go further on this work since it's published. 

ZhangLin

**Comment by MichaelLee-ceo** [comment]
Ok. Thanks for your reply!
